ENG-383 Basic AWS copilot
opencopilotdev/opencopilot pull request #90
Opened 2023-09-06 07:43 UTC by kristjanpeterson1

### Task / problem
Basic AWS CLI copilot

2023-09-06 10:03 UTC, taivop requested changes
Let's change subdirectory name to `aws_copilot`.

Other than that, my small test gave reasonable output so I would defer to @JohannesTK for further review.

2023-09-07 07:03 UTC, taivop approved these changes

2023-09-07 07:10 UTC, taivop approved these changes

2023-09-07 07:13 UTC, KasparPeterson approved these changes

2023-09-07 07:16 UTC, merged