Error handling (ENG-345)
opencopilotdev/opencopilot pull request #92
Opened 2023-09-06 10:01 UTC by KasparPeterson

2023-09-06 13:10 UTC, kristjanpeterson1 commented on opencopilot/application.py
> +from .domain import error_messages
opencopilot.domain?

2023-09-06 13:17 UTC, kristjanpeterson1 commented on opencopilot/domain/error_messages.py
> +    "http://localhost:8080 is wrong or Weaviate did not start up in the interval "
hmm this URL cannot be hardcoded I guess? Now its `settings.get().WEAVIATE_URL or "http://localhost:8080"` I think

2023-09-06 13:23 UTC, kristjanpeterson1 commented on requirements.txt
> +colorama==0.4.6
missing from setup.py?

2023-09-06 13:40 UTC, KasparPeterson commented on requirements.txt
> +colorama==0.4.6
It is actually a sub dependency already :)

2023-09-06 13:47 UTC, kgrofelnik commented on requirements.txt
> +colorama==0.4.6
Maybe we could do the [FastAPI trick ](https://github.com/tiangolo/fastapi/blob/master/requirements.txt)for `requirements.txt`:
`-e .[all]`

That way, we have only one place for maintaining the dependency list.

2023-09-07 07:51 UTC, taivop requested changes

2023-09-07 07:51 UTC, taivop commented on opencopilot/service/error_responses.py
> +class OpenAIUnavailableError(APIErrorResponse):
Nit - AFAICT this happens - among other things - when the OpenAI API key is wrong? IMO wrong api key does not mean OpenAI is unavailable.

2023-09-07 07:51 UTC, taivop commented on opencopilot/service/error_responses.py
> +        return status.HTTP_503_SERVICE_UNAVAILABLE
502 Bad Gateway is a better description of the reality I think? Or is 502 appropriate only when the server is a thin proxy (which OpenCopilot is not)?

2023-09-07 07:51 UTC, taivop commented on opencopilot/domain/cli/cli_chat_use_case.py
> +        raise CopilotIsNotRunningError(error_messages.COPILOT_IS_NOT_RUNNING_ERROR)
Perhaps we can add here the host:port that we tried to use to access the copilot -- it's a common source of bugs that the port is mismatching between where the host is started and what the client tries to connect to.

2023-09-07 07:51 UTC, taivop commented on opencopilot/domain/error_messages.py
> +    "http://localhost:8080 is wrong or Weaviate did not start up in the interval "
Here and in other Weaviate errors -- ideally we'd provide a link to setup instructions (or debugging when Weaviate is not working) - but we currently don't have that so nothing to add for now.

2023-09-07 07:51 UTC, taivop commented on opencopilot/domain/error_messages.py
> +    "Could not query Weaviate." "\nPlease make sure that Weaviate has data."
Above `WEAVIATE_QUERY_ERROR` is used as a message in a catch-all situation -- is it true that the "no data" scenario is the only situation where this will be thrown?

2023-09-07 09:32 UTC, KasparPeterson commented on opencopilot/service/error_responses.py
> +class OpenAIUnavailableError(APIErrorResponse):
@taivop What would you suggest to do in this case?
1. Rename to OpenAIError? So we have one error for all cases.
2. Try to catch all OpenAI errors separately? These are the errors currently:
  * APIError
  * TryAgain
  * Timeout
  * APIConnectionError
  * InvalidRequestError
  * AuthenticationError
  * PermissionError
  * RateLimitError
  * ServiceUnavailableError
  * InvalidAPIType
  * SignatureVerificationError
  This will fail in the long run for sure

2023-09-07 09:35 UTC, KasparPeterson commented on opencopilot/service/error_responses.py
> +        return status.HTTP_503_SERVICE_UNAVAILABLE
502 Bad Gateway is suitable. I was in between 502 vs 503.
GPT-4 seems to favour 502 as well. Will change

2023-09-07 09:38 UTC, KasparPeterson commented on opencopilot/domain/cli/cli_chat_use_case.py
> +        raise CopilotIsNotRunningError(error_messages.COPILOT_IS_NOT_RUNNING_ERROR)
Agreed!

2023-09-07 09:43 UTC, KasparPeterson commented on opencopilot/domain/error_messages.py
> +    "Could not query Weaviate." "\nPlease make sure that Weaviate has data."
This is more like a catch-all situation. Not fully sure about all the cases where it can return that error. Internally we are catching: `UnexpectedStatusCodeException`.

From source code it seems it can also happen in other Weaviate related cases:
* creating a backup 
* deleting data
* requesting weaviate status
* replace
* validate
* getting objects
* replacing objects
* etc...

Best error handling is still imo returning the error that the Weaviate itself is returning. Our goal is to essentially remove all internal errors and replace them with "one liner" explanations and this approach is the best I could come up with.

2023-09-07 10:11 UTC, taivop commented on opencopilot/service/error_responses.py
> +class OpenAIUnavailableError(APIErrorResponse):
I think `OpenAIError` rename would be best, would definitely want to catch everything separately (esp. since they will add new ones).

2023-09-07 10:19 UTC, KasparPeterson commented on opencopilot/domain/error_messages.py
> +    "Could not query Weaviate." "\nPlease make sure that Weaviate has data."
But are we showing the Weaviate own error msg?

Or do you mean we manually craft the exception message:
`error.messages.WEAVIATE_ERROR_MESSAGE + "\nFull Weaviate error message:" + weaviate_exc.message`?

2023-09-07 10:27 UTC, KasparPeterson commented on opencopilot/domain/error_messages.py
> +    "Could not query Weaviate." "\nPlease make sure that Weaviate has data."
Alternatively:

`weaviate_exc.message + "\nPlease make sure Weaviate is running and the data has been ingested"`

2023-09-07 10:27 UTC, taivop commented on opencopilot/domain/error_messages.py
> +    "Could not query Weaviate." "\nPlease make sure that Weaviate has data."
I'm not sure whether we are showing the Weaviate error msg; my point is that we _should_ show it so the user can debug. It is present in the stack trace, as the item right before ours, isn't it? If we are showing it already, then no change needed.

2023-09-07 11:06 UTC, taivop approved these changes

2023-09-07 11:12 UTC, merged